// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: db-queries.sql

package sql

import (
	"context"
)

const createSatcomData = `-- name: CreateSatcomData :exec
INSERT INTO common.satcom_data(company, category, "type", "date", "time", db_port, ui_port, url, ip, status)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateSatcomDataParams struct {
	Company  string `db:"company" json:"company"`
	Category string `db:"category" json:"category"`
	Type     string `db:"type" json:"type"`
	Date     string `db:"date" json:"date"`
	Time     string `db:"time" json:"time"`
	DbPort   string `db:"db_port" json:"db_port"`
	UiPort   string `db:"ui_port" json:"ui_port"`
	Url      string `db:"url" json:"url"`
	Ip       string `db:"ip" json:"ip"`
	Status   bool   `db:"status" json:"status"`
}

// --------------------- SATCOM DATA ------------------------------
func (q *Queries) CreateSatcomData(ctx context.Context, arg CreateSatcomDataParams) error {
	_, err := q.db.Exec(ctx, createSatcomData,
		arg.Company,
		arg.Category,
		arg.Type,
		arg.Date,
		arg.Time,
		arg.DbPort,
		arg.UiPort,
		arg.Url,
		arg.Ip,
		arg.Status,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO common.users(user_name, email, phone, pass, role) 
VALUES($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	UserName string `db:"user_name" json:"user_name"`
	Email    string `db:"email" json:"email"`
	Phone    string `db:"phone" json:"phone"`
	Pass     string `db:"pass" json:"pass"`
	Role     string `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserName,
		arg.Email,
		arg.Phone,
		arg.Pass,
		arg.Role,
	)
	return err
}

const deleteSatcomData = `-- name: DeleteSatcomData :exec
DELETE FROM common.satcom_data
WHERE id = $1
`

func (q *Queries) DeleteSatcomData(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSatcomData, id)
	return err
}

const getAllSatcomData = `-- name: GetAllSatcomData :many
SELECT id, company, category, "type", "date", "time", db_port, ui_port, url, ip, status
FROM common.satcom_data
ORDER BY id
`

func (q *Queries) GetAllSatcomData(ctx context.Context) ([]CommonSatcomDatum, error) {
	rows, err := q.db.Query(ctx, getAllSatcomData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommonSatcomDatum
	for rows.Next() {
		var i CommonSatcomDatum
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Category,
			&i.Type,
			&i.Date,
			&i.Time,
			&i.DbPort,
			&i.UiPort,
			&i.Url,
			&i.Ip,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id, user_name, email 
FROM common.users 
ORDER BY user_id
`

type GetAllUsersRow struct {
	UserID   int32  `db:"user_id" json:"user_id"`
	UserName string `db:"user_name" json:"user_name"`
	Email    string `db:"email" json:"email"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.UserID, &i.UserName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSatcomDataById = `-- name: GetSatcomDataById :one
SELECT id, company, category, "type", "date", "time", db_port, ui_port, url, ip, status
FROM common.satcom_data
WHERE id = $1
`

func (q *Queries) GetSatcomDataById(ctx context.Context, id int32) (CommonSatcomDatum, error) {
	row := q.db.QueryRow(ctx, getSatcomDataById, id)
	var i CommonSatcomDatum
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Category,
		&i.Type,
		&i.Date,
		&i.Time,
		&i.DbPort,
		&i.UiPort,
		&i.Url,
		&i.Ip,
		&i.Status,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_name, email, phone, pass, pss_valid, otp, otp_valid, otp_exp, role 
FROM common.users 
WHERE email = $1
`

// --------------------- AUTHENTICATION ------------------------------
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (CommonUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i CommonUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.Pass,
		&i.PssValid,
		&i.Otp,
		&i.OtpValid,
		&i.OtpExp,
		&i.Role,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT user_id, user_name, email, phone, pass, pss_valid, otp, otp_valid, otp_exp, role 
FROM common.users 
WHERE user_name = $1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (CommonUser, error) {
	row := q.db.QueryRow(ctx, getUserByUserName, userName)
	var i CommonUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.Pass,
		&i.PssValid,
		&i.Otp,
		&i.OtpValid,
		&i.OtpExp,
		&i.Role,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT user_id, user_name, email, phone, pass, pss_valid, otp, otp_valid, otp_exp, role 
FROM common.users 
WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (CommonUser, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i CommonUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.Pass,
		&i.PssValid,
		&i.Otp,
		&i.OtpValid,
		&i.OtpExp,
		&i.Role,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, user_name, email, phone, pass, pss_valid, otp, otp_valid, otp_exp, role 
FROM common.users 
WHERE user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, userID int32) (CommonUser, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i CommonUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.Pass,
		&i.PssValid,
		&i.Otp,
		&i.OtpValid,
		&i.OtpExp,
		&i.Role,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT user_id, user_name, email, phone, pass, pss_valid, otp, otp_valid, otp_exp, role 
FROM common.users 
WHERE user_name = $1 OR email = $1 OR phone = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, userName string) (CommonUser, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, userName)
	var i CommonUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.Pass,
		&i.PssValid,
		&i.Otp,
		&i.OtpValid,
		&i.OtpExp,
		&i.Role,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE common.users 
SET pass = $1, pss_valid = $2 
WHERE email = $3
`

type UpdatePasswordParams struct {
	Pass     string `db:"pass" json:"pass"`
	PssValid bool   `db:"pss_valid" json:"pss_valid"`
	Email    string `db:"email" json:"email"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Pass, arg.PssValid, arg.Email)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE common.users 
SET user_name = $1, email = $2, phone = $3, role = $4
WHERE user_id = $5
`

type UpdateUserParams struct {
	UserName string `db:"user_name" json:"user_name"`
	Email    string `db:"email" json:"email"`
	Phone    string `db:"phone" json:"phone"`
	Role     string `db:"role" json:"role"`
	UserID   int32  `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserName,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.UserID,
	)
	return err
}

const updateSatcomData = `-- name: UpdateSatcomData :exec
UPDATE common.satcom_data
SET company = $1, category = $2, "type" = $3, "date" = $4, "time" = $5, 
    db_port = $6, ui_port = $7, url = $8, ip = $9, status = $10
WHERE id = $11
`

type UpdateSatcomDataParams struct {
	Company  string `db:"company" json:"company"`
	Category string `db:"category" json:"category"`
	Type     string `db:"type" json:"type"`
	Date     string `db:"date" json:"date"`
	Time     string `db:"time" json:"time"`
	DbPort   string `db:"db_port" json:"db_port"`
	UiPort   string `db:"ui_port" json:"ui_port"`
	Url      string `db:"url" json:"url"`
	Ip       string `db:"ip" json:"ip"`
	Status   bool   `db:"status" json:"status"`
	ID       int32  `db:"id" json:"id"`
}

func (q *Queries) UpdateSatcomData(ctx context.Context, arg UpdateSatcomDataParams) error {
	_, err := q.db.Exec(ctx, updateSatcomData,
		arg.Company,
		arg.Category,
		arg.Type,
		arg.Date,
		arg.Time,
		arg.DbPort,
		arg.UiPort,
		arg.Url,
		arg.Ip,
		arg.Status,
		arg.ID,
	)
	return err
}
